# Generated by Django 3.1.2 on 2020-11-04 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0004_auto_20201104_0756'),
        ('generally', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_name', models.CharField(max_length=50)),
                ('percent', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('finish_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DiscountProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generally.discount')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tyres.tyres')),
            ],
        ),
    ]
