# Generated by Django 3.1.2 on 2020-11-05 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generally', '0003_auto_20201104_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='finish_date',
            new_name='expiry_date',
        ),
    ]
