# Generated by Django 3.1.2 on 2020-11-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generally', '0005_discount_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expiry_date',
            field=models.TimeField(),
        ),
    ]
