# Generated by Django 3.1.2 on 2020-11-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generally', '0006_auto_20201105_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
    ]
