# Generated by Django 3.1.2 on 2020-11-12 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0004_auto_20201104_0756'),
        ('generally', '0008_auto_20201112_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountproducts',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='tyres.tyres'),
        ),
    ]
