# Generated by Django 3.1.2 on 2020-11-04 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64, verbose_name='Marka')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CarMarka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=50, verbose_name='Marka')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tyres.carmarka', verbose_name='Marka')),
            ],
        ),
        migrations.CreateModel(
            name='CarMotor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor', models.CharField(max_length=50, verbose_name='Motor')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tyres.carmodel', verbose_name='Model')),
            ],
        ),
        migrations.CreateModel(
            name='Tyres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.CharField(max_length=64, verbose_name='En (mm)')),
                ('height', models.CharField(max_length=64, verbose_name='Hündürluk (%)')),
                ('radius', models.CharField(max_length=64, verbose_name='Radius (düym)')),
                ('klass', models.CharField(max_length=64, verbose_name='Klass')),
                ('price', models.FloatField(verbose_name='Qiymət')),
                ('year', models.PositiveIntegerField(verbose_name='İl')),
                ('country', models.CharField(max_length=64, verbose_name='Ölkə')),
                ('name', models.CharField(max_length=128, verbose_name='Ad')),
                ('published', models.BooleanField(default=False, verbose_name='published')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tyres.brand')),
                ('car', models.ManyToManyField(to='tyres.Car')),
            ],
        ),
        migrations.CreateModel(
            name='TyresImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='tyres/', verbose_name='Şəkil')),
                ('trye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tyres.tyres', verbose_name='Təkərin')),
            ],
        ),
        migrations.CreateModel(
            name='CarYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='İl')),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tyres.carmotor', verbose_name='Motor')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tyres.caryear', verbose_name='Maşının İli'),
        ),
        migrations.AddField(
            model_name='car',
            name='marka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tyres.carmarka', verbose_name='Maşının Markası'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tyres.carmodel', verbose_name='Maşının Modeli'),
        ),
        migrations.AddField(
            model_name='car',
            name='motor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tyres.carmotor', verbose_name='Maşının Motoru'),
        ),
    ]
