# Generated by Django 3.1.2 on 2020-11-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0002_remove_tyres_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyres',
            name='car',
            field=models.ManyToManyField(to='tyres.Car'),
        ),
    ]
